# Generated by Django 5.2.9 on 2026-01-07 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_dtm', models.DateTimeField(blank=True, null=True)),
                ('bill_start', models.DateTimeField(null=True)),
                ('bill_end', models.DateTimeField(null=True)),
                ('audit_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('PENDING_APPROVAL', 'Pending Approval'), ('UNUSABLE', 'Unusable')], default='PENDING_APPROVAL', max_length=100)),
                ('bill_transit', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('cost_mult', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('report', models.FileField(blank=True, upload_to='')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='usage.station')),
            ],
        ),
    ]
