# Generated by Django 5.2.9 on 2026-01-07 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('IBIBLIO_ADMIN', 'IBIBLIO_ADMIN'), ('STATION_ADMIN', 'STATION_ADMIN'), ('STATION_USER', 'STATION_USER')], default='STATION_USER', max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.station')),
            ],
        ),
    ]
